version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: gunshot-detector-backend
    ports:
      - "8000:8000"
    volumes:
      - temp-data:/app/temp
      - ./data:/app/data
      - ./ml:/app/ml
      - ./IA_EfficientNet_test:/app/IA_EfficientNet_test:ro
      - ./graphs:/app/graphs
    networks:
      - app-network
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import requests; requests.get('http://localhost:8000/health')",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gunshot-detector-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - BACKEND_API_URL=http://backend:8000
    volumes:
      - temp-data:/app/temp
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  temp-data:
  models-data:
